services:
  # Backend API server for the PG&E Substation Operations Assistant
  - type: web
    name: pge-substation-assistant
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node --optimize_for_size --max_old_space_size=512 --gc_interval=100 $(which npx) ts-node src/data-based-mock-server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4477
    healthCheckPath: /health

  # Frontend static site for the PG&E Substation Operations Assistant
  - type: web
    name: pge-substation-web
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build && cp -r build/* ../server/public/
    staticPublishPath: ./server/public
    routes:
      - type: rewrite
        source: /api/*
        destination: pge-substation-assistant 