services:
  # Combined Web Application and API
  - type: web
    name: pge-substation-assistant
    env: node
    buildCommand: cd server && npm install && npm install express-rate-limit jsonwebtoken @types/jsonwebtoken --save && cd ../client && npm install && npm run build && mkdir -p ../server/public && cp -r build/* ../server/public/
    startCommand: cd server && node --optimize_for_size --max_old_space_size=512 --gc_interval=100 $(which npx) ts-node src/web-server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /health
    
  # Frontend Web App
  - type: web
    name: pge-substation-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: pge-substation-assistant
          type: web
          property: url
        postfix: /api
    plan: free
    
  # Redirect the API to the backend
  - type: redirect
    name: pge-api-redirect
    source: 
      type: web
      name: pge-substation-web
      path: /api
    destination: 
      type: web
      name: pge-substation-assistant
      path: /api 